id: I6A6448FF
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-3c8e
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 21:54:18.192942+00:00
last_modified: 2023-09-29 21:54:18.192948+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG2144
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG2144
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན།
  languages:
  - bo
  author: སྤྱན་སྔ་བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.950729871560345
  ocr_word_median_confidence_index: 0.99701136
bases:
  I1KG2147:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2147
      total_pages: 944
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG2147.txt
    statistics:
      ocr_word_median_confidence_index: 0.9938397800000001
      ocr_word_mean_confidence_index: 0.9413351198620821
  I1KG2146:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2146
      total_pages: 880
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2146.txt
    statistics:
      ocr_word_median_confidence_index: 0.9994731
      ocr_word_mean_confidence_index: 0.9669403286113475
  I1KG2148:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2148
      total_pages: 842
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG2148.txt
    statistics:
      ocr_word_median_confidence_index: 0.9943708
      ocr_word_mean_confidence_index: 0.9441811941727448
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
